using System.Xml.Serialization;
using System.Collections.Generic;

namespace CiscoPCCE.Toolkit.Bean
{





// Path("machineinventory")
[XmlRoot("machine")]
public class MachineHost : BaseApiBean {
  private List<MachineAddress>? addresses;
  private bool? autoGenerated;
  private string? baseUrlfromRefUrl;
  private int? changeStamp;
  private string? correlationId;
  private ReferenceBean department;
  private string? description;
  private string? hostName;
  private string? idFromRefUrl;
  private MachineType machineType;
  private MachineVersion machineVersion;
  private string? name;
  private ReferenceBean peripheralSet;
  private string? refURL;
  private ReferenceBean vmHostRef;
  private string? vmInstanceUuid;

  [XmlElement("networks")]
  [XmlElement("network")]
  public List<MachineAddress>? Addresses
  {
      get => addresses;
      set => addresses = value;
  }


  public void setAddresses(List<MachineAddress> addresses) {
     this.addresses = addresses;
  }

  public bool? AutoGenerated
  {
      get => autoGenerated;
      set => autoGenerated = value;
  }


  public void setAutoGenerated(Boolean autoGenerated) {
     this.autoGenerated = autoGenerated;
  }

  public string? BaseUrlfromRefUrl
  {
      get => baseUrlfromRefUrl;
      set => baseUrlfromRefUrl = value;
  }


  public void setBaseUrlfromRefUrl(String baseUrlfromRefUrl) {
     this.baseUrlfromRefUrl = baseUrlfromRefUrl;
  }

  public int? ChangeStamp
  {
      get => changeStamp;
      set => changeStamp = value;
  }


  public void setChangeStamp(int? changeStamp) {
     this.changeStamp = changeStamp;
  }

  public string? CorrelationId
  {
      get => correlationId;
      set => correlationId = value;
  }


  public void setCorrelationId(String correlationId) {
     this.correlationId = correlationId;
  }

  public ReferenceBean Department
  {
      get => department;
      set => department = value;
  }


  public void setDepartment(ReferenceBean department) {
     this.department = department;
  }

  public string? Description
  {
      get => description;
      set => description = value;
  }


  public void setDescription(String description) {
     this.description = description;
  }

  public string? HostName
  {
      get => hostName;
      set => hostName = value;
  }


  public void setHostName(String hostName) {
     this.hostName = hostName;
  }

  public string? IdFromRefUrl
  {
      get => idFromRefUrl;
      set => idFromRefUrl = value;
  }


  public void setIdFromRefUrl(String idFromRefUrl) {
     this.idFromRefUrl = idFromRefUrl;
  }

  [XmlElement("type")]
  public MachineType MachineType
  {
      get => machineType;
      set => machineType = value;
  }


  public void setMachineType(MachineType machineType) {
     this.machineType = machineType;
  }

  [XmlElement("versionInfo")]
  public MachineVersion MachineVersion
  {
      get => machineVersion;
      set => machineVersion = value;
  }


  public void setMachineVersion(MachineVersion machineVersion) {
     this.machineVersion = machineVersion;
  }

  public string? Name
  {
      get => name;
      set => name = value;
  }


  public void setName(String name) {
     this.name = name;
  }

  [XmlElement("peripheralSet")]
  public ReferenceBean PeripheralSet
  {
      get => peripheralSet;
      set => peripheralSet = value;
  }


  public void setPeripheralSet(ReferenceBean peripheralSet) {
     this.peripheralSet = peripheralSet;
  }

  public string? RefURL
  {
      get => refURL;
      set => refURL = value;
  }


  public void setRefURL(String refURL) {
     this.refURL = refURL;
  }

  [XmlElement("vmHost")]
  public ReferenceBean VmHostRef
  {
      get => vmHostRef;
      set => vmHostRef = value;
  }


  public void setVmHostRef(ReferenceBean vmHostRef) {
     this.vmHostRef = vmHostRef;
  }

  public string? VmInstanceUuid
  {
      get => vmInstanceUuid;
      set => vmInstanceUuid = value;
  }


  public void setVmInstanceUuid(String vmInstanceUuid) {
     this.vmInstanceUuid = vmInstanceUuid;
  }


  // Path("machineinventory")
  [XmlRoot("results")]
  public class MachineHostList : BaseApiListBean<MachineHost> {
    [XmlElement("machines")]
    [XmlElement("machine")]
   
    public override List<MachineHost>? GetItems() => items;

    public override void SetItems(List<MachineHost>? value) => items = value;
    {
        return items;
    }

    public override void SetItems(List<MachineHost>? items)
    {
        this.items = items;
    }
  }
}

}