using System.Xml.Serialization;

using CiscoPCCE.Toolkit.Sdk;

namespace CiscoPCCE.Toolkit.Bean
{
    [XmlType("machine")]
    public class MachineHost : BaseApiBean
    {
        [XmlArray("networks")]
        [XmlArrayItem("network")]
        public List<MachineAddress>? Addresses { get; set; }

        [XmlElement("autoGenerated")]
        public bool? AutoGenerated { get; set; }

        [XmlElement("baseUrlfromRefUrl")]
        public string? BaseUrlfromRefUrl { get; set; }

        [XmlElement("changeStamp")]
        public new int? ChangeStamp { get; set; }

        [XmlElement("correlationId")]
        public string? CorrelationId { get; set; }

        [XmlElement("department")]
        public required ReferenceBean Department { get; set; }

        [XmlElement("description")]
        public string? Description { get; set; }

        [XmlElement("hostName")]
        public string? HostName { get; set; }

        [XmlElement("idFromRefUrl")]
        public string? IdFromRefUrl { get; set; }

        [XmlElement("type")]
        public MachineType MachineType { get; set; }

        [XmlElement("versionInfo")]
        public required MachineVersion MachineVersion { get; set; }

        [XmlElement("name")]
        public string? Name { get; set; }

        [XmlElement("peripheralSet")]
        public required ReferenceBean PeripheralSet { get; set; }

        [XmlElement("refURL")]
        public new string? RefURL { get; set; }

        [XmlElement("vmHost")]
        public required ReferenceBean VmHostRef { get; set; }

        [XmlElement("vmInstanceUuid")]
        public string? VmInstanceUuid { get; set; }
    }
}