using System.Xml.Serialization;

namespace CiscoPCCE.Toolkit.Bean
{
    // Path("machineinventory")
    [XmlRoot("service")]
    public class MachineService : BaseApiBean
    {
        public bool? AutoGenerated { get; set; }

        [XmlElement("components")]
        [XmlElement("component")]
        public List<MachineComponent>? Components { get; set; }

        public string? Description { get; set; }

        public string? EnablePassword { get; set; }

        public string? Name { get; set; }

        public string? Pairing { get; set; }

        public string? Password { get; set; }

        public int? Port { get; set; }

        public string? Status { get; set; }

        public ServiceType Type { get; set; }

        public string? Uri { get; set; }

        public string? UserName { get; set; }

        // Path("machineinventory")
        [XmlRoot("results")]
        public class MachineServiceList : BaseApiListBean<MachineService>
        {
            public override List<MachineService>? GetItems() => Items;

            public override void SetItems(List<MachineService>? value) => Items = value;
        }
    }
}