using System.Xml.Serialization;

namespace CiscoPCCE.Toolkit.Bean
{
    // Path("machineinventory")
    [XmlRoot("machine")]
    public class MachineHost : BaseApiBean
    {
        [XmlElement("networks")]
        [XmlElement("network")]
        public List<MachineAddress>? Addresses { get; set; }

        public bool? AutoGenerated { get; set; }

        public string? BaseUrlfromRefUrl { get; set; }

        public new int? ChangeStamp { get; set; }

        public string? CorrelationId { get; set; }

        public required ReferenceBean Department { get; set; }

        public string? Description { get; set; }

        public string? HostName { get; set; }

        public string? IdFromRefUrl { get; set; }

        [XmlElement("type")]
        public MachineType MachineType { get; set; }

        [XmlElement("versionInfo")]
        public required MachineVersion MachineVersion { get; set; }

        public string? Name { get; set; }

        [XmlElement("peripheralSet")]
        public required ReferenceBean PeripheralSet { get; set; }

        public new string? RefURL { get; set; }

        [XmlElement("vmHost")]
        public required ReferenceBean VmHostRef { get; set; }

        public string? VmInstanceUuid { get; set; }

        // Path("machineinventory")
        [XmlRoot("results")]
        public class MachineHostList : BaseApiListBean<MachineHost>
        {
            public override List<MachineHost>? GetItems() => Items;

            public override void SetItems(List<MachineHost>? value) => Items = value;
        }
    }
}