using System.Xml.Serialization;

using CiscoPCCE.Toolkit.Sdk;

namespace CiscoPCCE.Toolkit.Bean
{
    // Path("machineinventory")
    [XmlRoot("service")]
    public class MachineService : BaseApiBean
    {
        [XmlElement("autoGenerated")]
        public bool? AutoGenerated { get; set; }

        [XmlArray("components")]
        [XmlArrayItem("component")]
        public List<MachineComponent>? Components { get; set; }

        [XmlElement("description")]
        public string? Description { get; set; }

        [XmlElement("enablePassword")]
        public string? EnablePassword { get; set; }

        [XmlElement("name")]
        public string? Name { get; set; }

        [XmlElement("pairing")]
        public string? Pairing { get; set; }

        [XmlElement("password")]
        public string? Password { get; set; }

        [XmlElement("port")]
        public int? Port { get; set; }

        [XmlElement("status")]
        public string? Status { get; set; }

        [XmlElement("type")]
        public ServiceType Type { get; set; }

        [XmlElement("uri")]
        public string? Uri { get; set; }

        [XmlElement("userName")]
        public string? UserName { get; set; }
    }
}