// ----------------------------------------------
package com.cisco.ccbu.cce.unifiedconfig.toolkit.bean;

public enum DeploymentModel {
  LOGGERB,
  LOGGERA,
  NOT_INITIALIZED,
  NON_DISTRIBUTOR,
  GENERAL,
  VRU,
  ROUTERLOGGER12000AGENTS,
  CCEPACM1,
  ROGGER4000AGENTS,
  CCEPACM1LAB,
  UCCE450AGENTSPROGGER,
  ROGGER2000AGENTS,
  PCCE4000AGENTS,
  PCCE12000AGENTS,
  ROUTERLOGGER24000AGENTS
}
